# Generated by Django 5.2.5 on 2025-08-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_taskresult_task_name_alter_taskresult_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskresult',
            name='task_name',
            field=models.CharField(choices=[('task_1', 'Task 1'), ('task_2', 'Task 2'), ('task_3', 'Task 3'), ('unknown_task', 'Unknown Task')], default='unknown-task'),
        ),
    ]
