# Generated by Django 5.2.5 on 2025-08-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_taskresult_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskresult',
            name='task_args',
            field=models.JSONField(null=True),
        ),
    ]
