# Generated by Django 5.2.5 on 2025-08-22 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_taskresult_task_args'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskresult',
            old_name='task_args',
            new_name='task_arg',
        ),
    ]
